version: '3'
services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_DATABASE: lamp
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./.dockers/mysql-datadir:/var/lib/mysql
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            retries: 10

    web:
        image: nginx:latest
        ports:
            - "${DR_PORT}:${DR_PORT}"
        volumes:
            - ./code:/code
			- ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - db

    php:
        build: ./php
        links: [ db ]
        ports:
            - "9000:9000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            DBUSER: lamp
            DBPASS: lamp
            DBNAME: lamp
            DBHOST: db
        volumes:
            - ./code:/code
			- ./archive.tgz:/tmp/archive.tgz
