version: '3'
services:
    ldap:
        image: osixia/openldap:stable
        environment:
            LDAP_ORGANISATION: $LDAP_ORGANISATION
            LDAP_DOMAIN: $LDAP_DOMAIN
            LDAP_ADMIN_PASSWORD: $LDAP_ADMIN_PASSWORD
            LDAP_BASE_DN: $LDAP_BASE_DN

            LDAP_READONLY_USER: "$LDAP_READONLY_USER"
            LDAP_READONLY_USER_USERNAME: $LDAP_READONLY_USER_USERNAME
            LDAP_READONLY_USER_PASSWORD: $LDAP_READONLY_USER_PASSWORD

            LDAP_TLS_CRT_FILENAME: cert1.pem
            LDAP_TLS_KEY_FILENAME: privkey1.pem
            LDAP_TLS_CA_CRT_FILENAME: fullchain1.pem
            LDAP_TLS_VERIFY_CLIENT: never

            LDAP_REPLICATION: "true"
            LDAP_REPLICATION_HOSTS: "#PYTHON2BASH:['ldap://ldap','ldap://$REPLICATION_HOST']"
        volumes:
            - ldap:/var/lib/ldap
            - slapd:/etc/ldap/slapd.d
            - ./apache/batch.org.uk:/container/service/slapd/assets/certs
            - ./ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom
            - ./other-scripts:/other-scripts
        ports:
            - 389:389
            - 636:636
        hostname: ldap
        extra_hosts:
                - "trafalgar.batch.org.uk:192.168.51.4"
                - "tobias.batch.org.uk:192.168.51.191"
        # command: --copy-service
        restart: always
        command: --copy-service --loglevel debug

    ldapadmin:
        image: dinkel/phpldapadmin
        links:
            - ldap:openldap
        ports:
            - 8081:80
        environment:
            LDAP_SERVER_HOST: ldap
            LDAP_SERVER_PORT: 389
        restart: always

    postfix:
        image: catatnight/postfix
        environment:
            maildomain: $MAIL_DOMAIN
            smtp_user: "${MAIL_SMTP_USER}:${MAIL_SMTP_PASS}"
        restart: unless-stopped
        restart: always

    self-service-password:
        image: dtwardow/ldap-self-service-password
        links:
            - ldap:ldap
            - postfix:mail
        ports:
            - 8082:80
        hostname: intranet.neontribe.net
        environment:
            LDAP_BASE: "${LDAP_BASE_DN}"
            LDAP_USER: "cn=admin,${LDAP_BASE_DN}"
            LDAP_PASS: "${LDAP_ADMIN_PASSWORD}"
            SMTP_HOST: mail
            SMTP_FROM: ldap@neontribe.org
            SMTP_USER: ${MAIL_SMTP_USER}
            SMTP_PASS: ${MAIL_SMTP_PASS}
            SERVER_HOSTNAME: intranet.neontribe.net
        restart: always

# docker exec -ti openvpn show-client-config

volumes:
    ldap:
    slapd:
