version: '3'
services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_DATABASE: lamp
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./mysql-datadir:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        # restart: always
        healthcheck:
            test: ["mysql", "-u", "lamp", "-plamp", "lamp", "-e", "'select count(*)'", "from", "users"]
            interval: 20s
            retries: 10

    php:
        build: .
        links: [ db ]
        ports:
            - "${DR_PORT}:${DR_PORT}"
        env_file:
            .env
        depends_on:
            - db
        volumes:
            - ./code:/code
        healthcheck:
            test: ["CMD", "nc" ,"-z", "localhost", "${DR_PORT}"]
            interval: 20s
            retries: 10
