version: '3'
services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_DATABASE: lamp
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./mysql-datadir:/var/lib/mysql
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            retries: 10

    php:
        build: ./php
        links: [ db ]
        ports:
            - "9000:9000"
        depends_on:
            - db
        environment:
            DBUSER: lamp
            DBPASS: lamp
            DBNAME: lamp
            DBHOST: db
        volumes:
            - ./code:/code
            - ./archive.tgz:/tmp/archive.tgz

    web:
        image: nginx:latest
        ports:
            - "${DR_PORT}:80"
        depends_on:
            - php
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - db
