version: '2.1'
services:
    db:
        image: mysql:5.6
        environment:
            MYSQL_USER: lamp
            MYSQL_PASSWORD: lamp
            MYSQL_DATABASE: lamp
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./mysql-datadir:/var/lib/mysql
        restart: always
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            interval: 20s
            retries: 10

    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        image: tobybatch/php
        links: [ db ]
        ports:
            - "9000:9000"
        depends_on:
            db:
                condition: service_healthy
        environment:
            DBUSER: lamp
            DBPASS: lamp
            DBNAME: lamp
            DBHOST: db
        volumes:
            - ./code:/code
